#cloud-config

coreos:
  etcd:
      name: node400
      addr: {{ .IP }}:4001
      peer-addr: {{ .IP }}:7001
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: docker.service
      drop-ins:
        - name: 50-insecure-registry.conf
          content: |
            [Service]
            Environment=DOCKER_OPTS='--insecure-registry="10.0.1.0/24"'
